Created At: 2026-06-09T15:02:49Z
Completed At: 2026-06-09T15:02:55Z

				The command completed successfully.
				Output:
				=== Step 1418 ===
{
  "step_index": 1418,
  "source": "MODEL",
  "type": "VIEW_FILE",
  "status": "DONE",
  "created_at": "2026-06-09T15:01:06Z",
  "content": "Created At: 2026-06-09T15:01:06Z\nCompleted At: 2026-06-09T15:01:06Z\nFile Path: `file:///c:/Users/User/Desktop/Portfolio/src/components/scenes/EarthZoom.jsx`\nTotal Lines: 93\nTotal Bytes: 2940\nShowing lines 1 to 93\nThe following code has been modified to include a line number before every line, in the format: <line_number>: <original_line>. Please note that any changes targeting the original code should remove the line number, colon, and leading space.\n1: \n2: /* ===== 3D Earth with Zoom Animation ===== */\n3: function Earth({ zoomStage, onArrived }) {\n4:   const earthRef = useRef();\n5:   const groupRef = useRef();\n6:   const cameraTarget = useRef(new THREE.Vector3(0, 0, 0));\n7:   const targetRotYRef = useRef(0);\n8: \n9:   // Fallback procedural textures\n10:   const proceduralTextures = useMemo(() => createEarthTextures(), []);\n11: \n12:   // State for high-res photorealistic textures\n13:   const [textures, setTextures] = useState(null);\n14: \n15:   useEffect(() => {\n16:     const loader = new THREE.TextureLoader();\n17:     loader.setCrossOrigin('anonymous');\n18: \n19:     let isMounted = true;\n20: \n21:     // Load photorealistic NASA textures from CDN\n22:     Promise.all([\n23:       new Promise((resolve) => {\n24:         loader.load(\n25:           'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',\n26:           (texture) => {\n27:             texture.colorSpace = THREE.SRGBColorSpace;\n28:             resolve(texture);\n29:           },\n30:           undefined,\n31:           () => resolve(null)\n32:         );\n33:       }),\n34:       new Promise((resolve) => {\n35:         loader.load(\n36:           'https://unpkg.com/three-globe/example/img/earth-night.jpg',\n37:           (texture) => {
<truncated 136 bytes>
      })\n44:     ]).then(([diffuse, emissive]) => {\n45:       if (!isMounted) return;\n46:       if (diffuse && emissive) {\n47:         se\n48:         break;\n49:       case 1: // Rotating to show India\n50:         targetPos = new THREE.Vector3(0, 0.08, 4.5);\n51:         lookTarget = new THREE.Vector3(0, 0.04, 0);\n52:         break;\n53:       case 2: // Approaching India\n54:         targetPos = new THREE.Vector3(0, MUMBAI_OFFSET_Y * 0.7, 3.4);\n55:         lookTarget = new THREE.Vector3(0, MUMBAI_OFFSET_Y * 0.6, 0);\n56:         break;\n57:       case 3: // Close to India — Mumbai region\n58:         targetPos = new THREE.Vector3(0, MUMBAI_OFFSET_Y + 0.05, 2.85);\n59:         lookTarget = new THREE.Vector3(0, MUMBAI_OFFSET_Y, 0);\n60:         break;\n61:       case 4: // Arrived at Mumbai\n62:         targetPos = new THREE.Vector3(0, MUMBAI_OFFSET_Y + 0.08, 2.65);\n63:         lookTarget = new THREE.Vector3(0, MUMBAI_OFFSET_Y + 0.04, 0);\n64:         onArrived();\n65:         break;\n66:       default:\n67:         targetPos = new THREE.Vector3(0, MUMBAI_OFFSET_Y + 0.08, 2.65);\n68:         lookTarget = new THREE.Vector3(0, MUMBAI_OFFSET_Y + 0.04, 0);\n69:     }\n70: \n71:     cam.position.lerp(targetPos, 0.025);\n72:     cameraTarget.current.lerp(lookTarget, 0.025);\n73:     cam.lookAt(cameraTarget.current);\n74:   });\n75: \n76:   return (\n77:     <group ref={groupRef}>\n78:       {/* Earth body */}\n79:       <mesh ref={earthRef}>\n80:         <sphereGeometry args={[2, 96, 96]} />\n81:         <meshStandardMaterial\n82:           map={activeTextures.diffuse}\n83:           roughness={0.6}\n84:           metalness={0.1}\n85:           emissiveMap={activeTextures.emissive}\n86:           emissive={new THREE.Color(isProcedural ? '#ffda73' : '#ffffff')}\n87:           emissiveIntensity={isProcedural ? 0.6 : 1.2}\n88:         />\n89:       </mesh>\n90: \n91:       {/* Cloud layer */}\n92:       <CloudLayer />\n93: \nThe above content shows the entire, complete file contents of the requested file.\n"
}

