export const certificates = [
  {
    id: 'cert-1',
    name: 'Python Programming Fundamentals',
    issuer: 'Coursera / Google',
    date: '2025',
    skills: ['Python', 'Programming Logic', 'Data Structures'],
    verifyLink: '#',
    color: '#3776AB',
  },
  {
    id: 'cert-2',
    name: 'Web Development Bootcamp',
    issuer: 'Udemy',
    date: '2025',
    skills: ['HTML', 'CSS', 'JavaScript', 'Responsive Design'],
    verifyLink: '#',
    color: '#E34F26',
  },
  {
    id: 'cert-3',
    name: 'Introduction to AI',
    issuer: 'IBM / Coursera',
    date: '2025',
    skills: ['AI Fundamentals', 'Machine Learning Basics', 'Neural Networks'],
    verifyLink: '#',
    color: '#00f0ff',
  },
  {
    id: 'cert-4',
    name: 'Git & GitHub Masterclass',
    issuer: 'Udemy',
    date: '2025',
    skills: ['Git', 'GitHub', 'Version Control', 'Collaboration'],
    verifyLink: '#',
    color: '#F05032',
  },
  {
    id: 'cert-5',
    name: 'Data Science with Python',
    issuer: 'Coursera',
    date: '2026',
    skills: ['Pandas', 'NumPy', 'Data Visualization', 'Statistics'],
    verifyLink: '#',
    color: '#a855f7',
  },
];
